public class tdmSvc {
    public class FillTreeList_element {
        public String url;
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'url'};
    }
    public class FillFolder3SubFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillFolder3SubFoldersResult;
        private String[] FillFolder3SubFoldersResult_type_info = new String[]{'FillFolder3SubFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillFolder3SubFoldersResult'};
    }
    public class FillFolder5SubFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillFolder5SubFoldersResult;
        private String[] FillFolder5SubFoldersResult_type_info = new String[]{'FillFolder5SubFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillFolder5SubFoldersResult'};
    }
    public class FillFolder4SubFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class FillTreeListResponse_element {
        public tdmSvc.ArrayOfLocation FillTreeListResult;
        private String[] FillTreeListResult_type_info = new String[]{'FillTreeListResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillTreeListResult'};
    }
    public class DeleteAFile_element {
        public String FileName;
        public String documentName;
        public String siteURL;
        private String[] FileName_type_info = new String[]{'FileName','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] documentName_type_info = new String[]{'documentName','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] siteURL_type_info = new String[]{'siteURL','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FileName','documentName','siteURL'};
    }
    public class FillFolderSubFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillFolderSubFoldersResult;
        private String[] FillFolderSubFoldersResult_type_info = new String[]{'FillFolderSubFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillFolderSubFoldersResult'};
    }
    public class FillFolder5SubFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class FillFolder2SubFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillFolder2SubFoldersResult;
        private String[] FillFolder2SubFoldersResult_type_info = new String[]{'FillFolder2SubFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillFolder2SubFoldersResult'};
    }
    public class DownloadPDFsResponse_element {
        public tdmSvc.JobStatus DownloadPDFsResult;
        private String[] DownloadPDFsResult_type_info = new String[]{'DownloadPDFsResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'DownloadPDFsResult'};
    }
    public class FillFolder2SubFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class JobStatus {
        public Boolean Status;
        public String Message;
        private String[] Status_type_info = new String[]{'Status','http://www.inpro.com/TDM/ServiceLayer/',null,'1','1','false'};
        private String[] Message_type_info = new String[]{'Message','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'Status','Message'};
    }
    public class FillFolderSubFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class DeleteAFileResponse_element {
        public tdmSvc.JobStatus DeleteAFileResult;
        private String[] DeleteAFileResult_type_info = new String[]{'DeleteAFileResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'DeleteAFileResult'};
    }
    public class ArrayOfLocation {
        public tdmSvc.Location[] Location;
        private String[] Location_type_info = new String[]{'Location','http://www.inpro.com/TDM/ServiceLayer/',null,'0','-1','true'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'Location'};
    }
    public class FillFolder4SubFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillFolder4SubFoldersResult;
        private String[] FillFolder4SubFoldersResult_type_info = new String[]{'FillFolder4SubFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillFolder4SubFoldersResult'};
    }
    public class UploadDocumentResponse_element {
        public tdmSvc.JobStatus UploadDocumentResult;
        private String[] UploadDocumentResult_type_info = new String[]{'UploadDocumentResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'UploadDocumentResult'};
    }
    public class FillListFoldersResponse_element {
        public tdmSvc.ArrayOfLocation FillListFoldersResult;
        private String[] FillListFoldersResult_type_info = new String[]{'FillListFoldersResult','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FillListFoldersResult'};
    }
    public class UploadDocument_element {
        public String FileId;        
        private String[] FileId_type_info = new String[]{'FileId','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};        
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'FileId'};
    }
    public class FillListFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class FillFolder3SubFolders_element {
        public tdmSvc.Location ListFolders;
        public String url;
        private String[] ListFolders_type_info = new String[]{'ListFolders','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] url_type_info = new String[]{'url','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListFolders','url'};
    }
    public class DownloadPDFs_element {
        public String jsonPDFList;
        private String[] jsonPDFList_type_info = new String[]{'jsonPDFList','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'jsonPDFList'};
    }
    public class Location {
        public String ListTitle;
        public String Type_x;
        public String FolderName;
        public String FolderRelativeUrl;
        public String SubFolderName;
        public String SubFolderRelativeUrl;
        public String SubFolderName2;
        public String SubFolderRelativeUrl2;
        public String SubFolderName3;
        public String SubFolderRelativeUrl3;
        public String SubFolderName4;
        public String SubFolderRelativeUrl4;
        public String SubFolderName5;
        public String SubFolderRelativeUrl5;
        public String SubFolderName6;
        public String SubFolderRelativeUrl6;
        public String SubFolderName7;
        public String SubFolderRelativeUrl7;
        public String SubFolderName8;
        public String SubFolderRelativeUrl8;
        public String SubFolderName9;
        public String SubFolderRelativeUrl9;
        public String SubFolderName10;
        public String SubFolderRelativeUrl10;
        private String[] ListTitle_type_info = new String[]{'ListTitle','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] Type_x_type_info = new String[]{'Type','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] FolderName_type_info = new String[]{'FolderName','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] FolderRelativeUrl_type_info = new String[]{'FolderRelativeUrl','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName_type_info = new String[]{'SubFolderName','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl_type_info = new String[]{'SubFolderRelativeUrl','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName2_type_info = new String[]{'SubFolderName2','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl2_type_info = new String[]{'SubFolderRelativeUrl2','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName3_type_info = new String[]{'SubFolderName3','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl3_type_info = new String[]{'SubFolderRelativeUrl3','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName4_type_info = new String[]{'SubFolderName4','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl4_type_info = new String[]{'SubFolderRelativeUrl4','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName5_type_info = new String[]{'SubFolderName5','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl5_type_info = new String[]{'SubFolderRelativeUrl5','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName6_type_info = new String[]{'SubFolderName6','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl6_type_info = new String[]{'SubFolderRelativeUrl6','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName7_type_info = new String[]{'SubFolderName7','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl7_type_info = new String[]{'SubFolderRelativeUrl7','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName8_type_info = new String[]{'SubFolderName8','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl8_type_info = new String[]{'SubFolderRelativeUrl8','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName9_type_info = new String[]{'SubFolderName9','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl9_type_info = new String[]{'SubFolderRelativeUrl9','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderName10_type_info = new String[]{'SubFolderName10','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] SubFolderRelativeUrl10_type_info = new String[]{'SubFolderRelativeUrl10','http://www.inpro.com/TDM/ServiceLayer/',null,'0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/','true','false'};
        private String[] field_order_type_info = new String[]{'ListTitle','Type_x','FolderName','FolderRelativeUrl','SubFolderName','SubFolderRelativeUrl','SubFolderName2','SubFolderRelativeUrl2','SubFolderName3','SubFolderRelativeUrl3','SubFolderName4','SubFolderRelativeUrl4','SubFolderName5','SubFolderRelativeUrl5','SubFolderName6','SubFolderRelativeUrl6','SubFolderName7','SubFolderRelativeUrl7','SubFolderName8','SubFolderRelativeUrl8','SubFolderName9','SubFolderRelativeUrl9','SubFolderName10','SubFolderRelativeUrl10'};
    }
    public class TDMServiceSoap {
        public String endpoint_x = GlobalHelper.GetTDMServiceEndpoint();
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'http://www.inpro.com/TDM/ServiceLayer/', 'tdmSvc'};
        public tdmSvc.JobStatus DownloadPDFs(String jsonPDFList) {
            tdmSvc.DownloadPDFs_element request_x = new tdmSvc.DownloadPDFs_element();
            request_x.jsonPDFList = jsonPDFList;
            tdmSvc.DownloadPDFsResponse_element response_x;
            Map<String, tdmSvc.DownloadPDFsResponse_element> response_map_x = new Map<String, tdmSvc.DownloadPDFsResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/DownloadPDFs',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'DownloadPDFs',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'DownloadPDFsResponse',
              'tdmSvc.DownloadPDFsResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DownloadPDFsResult;
        }
        public tdmSvc.ArrayOfLocation FillFolder4SubFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillFolder4SubFolders_element request_x = new tdmSvc.FillFolder4SubFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillFolder4SubFoldersResponse_element response_x;
            Map<String, tdmSvc.FillFolder4SubFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillFolder4SubFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillFolder4SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder4SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder4SubFoldersResponse',
              'tdmSvc.FillFolder4SubFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillFolder4SubFoldersResult;
        }
        public tdmSvc.ArrayOfLocation FillTreeList(String url) {
            tdmSvc.FillTreeList_element request_x = new tdmSvc.FillTreeList_element();
            request_x.url = url;
            tdmSvc.FillTreeListResponse_element response_x;
            Map<String, tdmSvc.FillTreeListResponse_element> response_map_x = new Map<String, tdmSvc.FillTreeListResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillTreeList',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillTreeList',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillTreeListResponse',
              'tdmSvc.FillTreeListResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillTreeListResult;
        }
        public tdmSvc.ArrayOfLocation FillListFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillListFolders_element request_x = new tdmSvc.FillListFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillListFoldersResponse_element response_x;
            Map<String, tdmSvc.FillListFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillListFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillListFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillListFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillListFoldersResponse',
              'tdmSvc.FillListFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillListFoldersResult;
        }
        public tdmSvc.ArrayOfLocation FillFolder3SubFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillFolder3SubFolders_element request_x = new tdmSvc.FillFolder3SubFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillFolder3SubFoldersResponse_element response_x;
            Map<String, tdmSvc.FillFolder3SubFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillFolder3SubFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillFolder3SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder3SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder3SubFoldersResponse',
              'tdmSvc.FillFolder3SubFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillFolder3SubFoldersResult;
        }
        public tdmSvc.ArrayOfLocation FillFolder5SubFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillFolder5SubFolders_element request_x = new tdmSvc.FillFolder5SubFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillFolder5SubFoldersResponse_element response_x;
            Map<String, tdmSvc.FillFolder5SubFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillFolder5SubFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillFolder5SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder5SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder5SubFoldersResponse',
              'tdmSvc.FillFolder5SubFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillFolder5SubFoldersResult;
        }
        public tdmSvc.JobStatus DeleteAFile(String FileName,String documentName,String siteURL) {
            tdmSvc.DeleteAFile_element request_x = new tdmSvc.DeleteAFile_element();
            request_x.FileName = FileName;
            request_x.documentName = documentName;
            request_x.siteURL = siteURL;
            tdmSvc.DeleteAFileResponse_element response_x;
            Map<String, tdmSvc.DeleteAFileResponse_element> response_map_x = new Map<String, tdmSvc.DeleteAFileResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/DeleteAFile',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'DeleteAFile',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'DeleteAFileResponse',
              'tdmSvc.DeleteAFileResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.DeleteAFileResult;
        }
        public tdmSvc.ArrayOfLocation FillFolder2SubFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillFolder2SubFolders_element request_x = new tdmSvc.FillFolder2SubFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillFolder2SubFoldersResponse_element response_x;
            Map<String, tdmSvc.FillFolder2SubFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillFolder2SubFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillFolder2SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder2SubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolder2SubFoldersResponse',
              'tdmSvc.FillFolder2SubFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillFolder2SubFoldersResult;
        }
        public tdmSvc.ArrayOfLocation FillFolderSubFolders(tdmSvc.Location ListFolders,String url) {
            tdmSvc.FillFolderSubFolders_element request_x = new tdmSvc.FillFolderSubFolders_element();
            request_x.ListFolders = ListFolders;
            request_x.url = url;
            tdmSvc.FillFolderSubFoldersResponse_element response_x;
            Map<String, tdmSvc.FillFolderSubFoldersResponse_element> response_map_x = new Map<String, tdmSvc.FillFolderSubFoldersResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/FillFolderSubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolderSubFolders',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'FillFolderSubFoldersResponse',
              'tdmSvc.FillFolderSubFoldersResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.FillFolderSubFoldersResult;
        }
        public tdmSvc.JobStatus UploadDocument(String FileId) {
            tdmSvc.UploadDocument_element request_x = new tdmSvc.UploadDocument_element();
            request_x.FileId = FileId;            
            tdmSvc.UploadDocumentResponse_element response_x;
            Map<String, tdmSvc.UploadDocumentResponse_element> response_map_x = new Map<String, tdmSvc.UploadDocumentResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://www.inpro.com/TDM/ServiceLayer/UploadDocument',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'UploadDocument',
              'http://www.inpro.com/TDM/ServiceLayer/',
              'UploadDocumentResponse',
              'tdmSvc.UploadDocumentResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.UploadDocumentResult;
        }
    }
}